<!--STARTFOOTER-->
    <nav class="footer-links">
      <div class="container">
        <div class="footer-links__column">
          <ul>
            <li>
              <a href="https://github.com/18F/fec">GitHub repository</a>
            </li>
            <li>
              <a href="https://github.com/18F/FEC/blob/master/release_notes/release_notes.md">Release notes</a>
            </li>
          </ul>
          <ul>
            <li>
              <a href="contact-us/">Contact us</a>
            </li>
            <li>
              <a href="about/">About</a>
            </li>
            <li>
              <a href="http://beta.fec.gov/press/">Press</a>
            </li>
            <li>
              <a href="updates/">Latest updates</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <footer class="footer">
      <div class="container">
        <div class="seal">
          <img class="seal__img" width="140" height="140" src="https://beta.fec.gov/static/img/seal--inverse.svg" alt="Seal of the Federal Election Commission | United States of America">
          <p class="address__title">Federal Election Commission</p>
        </div>

        <div class="address">
          <ul class="social-media">
            <li>
              <div class="i icon--twitter">
                <a href="https://twitter.com/fec"><span class="u-visually-hidden">The FEC's Twitter page</span></a>
              </div>
            </li>
            <li>
              <div class="i icon--youtube">
                <a href="https://www.youtube.com/user/FECTube"><span class="u-visually-hidden">The FEC's YouTube page</span></a>
              </div>
            </li>
          </ul>

          <p>999 E Street, NW<br>
          Washington, DC 20463</p>
          <p>(800) 424-9530</p>
        </div>
      </div>
    </footer>

    <div id="glossary" class="glossary"
    aria-describedby="glossary-result" aria-hidden="true">
  <button
      title="Close glossary"
      class="button button--close--inverse toggle js-glossary-close"
    ><span class="u-visually-hidden">Hide glossary</span>
  </button>
  <h2>Glossary</h2>
  <label for="glossary-search" class="label">Search terms</label>
  <input id="glossary-search" class="glossary__search js-glossary-search" type="search">
  <span class="t-note t-sans search__example">Examples: receipt; Hybrid PAC</span>
  <div class="glossary__content" id="glossary-result">
    <ul class="glossary__list js-glossary-list accordion--inverse"></ul>
  </div>
</div>


    <script>
      window.FEC_APP_URL = 'https://beta.fec.gov/data';
      window.API_LOCATION = 'https://api.open.fec.gov';
      window.API_VERSION = 'v1';
      window.API_KEY = 'oXyFx4md0kTkxxq9JNfIRlrOPorXc60dqOVEs4GE';
    </script>

    
    <script type="text/javascript" src="/app_javascript/main.js"></script>
    
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('set', 'anonymizeIp', true);
      ga('set', 'forceSSL', true);
      ga('create', 'UA-48605964-22', 'auto');
      ga('send', 'pageview');
    </script>
    <script id="_fed_an_ua_tag" src="https://dap.digitalgov.gov/Universal-Federated-Analytics-Min.js?agency=FEC"></script>
    <script>
      function goBack() {
          window.history.back();
      }
    </script>
<!--ENDFOOTER-->