<!--STARTNAV-->
    <a href="#main" class="skip-nav">skip navigation</a>
    <div class="js-banner new-site-banner slab--neutral">
      <div class="js-banner-min container" aria-hidden="false">
        <p class="t-sans">Welcome to the new fec.gov &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;| &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; If you can't find what you need, use the <a href="http://www.fec.gov">classic FEC.gov</a></p>
        <button class="js-open-banner button--open">Show more</button>
      </div>
      <div class="js-banner-max container" aria-hidden="true">
        <p class="t-sans"><strong>Welcome to the new fec.gov</strong> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;| &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; If you can't find what you need, use <a href="http://www.fec.gov">classic.fec.gov</a></p>
        <p><a class="button button--cta button--primary button--tour">START THE TOUR</a></p>
        <p class="t-sans">Questions or comments? use the <a>anonymous feedback tool</a> or email us at <a>betafeedback@fec.gov</a></p>
        <button class="js-close-banner button--close">Show less</button>
      </div>
    </div>
    
    <header class="site-header">
      <div class="masthead">
        <div class="disclaimer">
          <span class="disclaimer__right">An official website of the United States Government <img src="/static/img/us_flag_small.png"  alt="US flag signifying that this is a United States Federal Government website"></span>
        </div>
        <img src="/static/img/print-logo.png" class="u-print-only" alt="FEC logo">
        <a title="Home" href="" class="site-title"><span class="u-visually-hidden">Federal Election Commission | United States of America</span></a>
        <ul class="utility-nav list--flat">
          <li class="utility-nav__item"><a href="calendar/">Calendar</a></li>
          <li class="utility-nav__item"><button class="js-glossary-toggle glossary__toggle">Glossary</button></li>
        </ul>
      </div>
      <nav class="site-nav js-site-nav">
        <div id="site-menu" class="site-nav__container">
          <ul class="site-nav__panel site-nav__panel--main">
            <li><h3 class="site-nav__title u-under-lg-only">Menu</h3></li>
            <li class="site-nav__item" data-submenu="data">
              <a class="site-nav__link u-lg-only" href="https://beta.fec.gov/data">
                <span class="site-nav__link__title">Campaign finance data</span>
              </a>
              <button class="site-nav__link button--nav-panel js-panel-trigger u-under-lg-only" aria-controls="nav-data">Campaign finance data</button>
            </li>
            <li class="site-nav__item site-nav__item--secondary" data-submenu="services">
              <a href="https://beta.fec.gov/registration-and-reporting/" class="site-nav__link">
                <span class="site-nav__link__title">Candidate and committee services</span>
              </a>
            </li>
            <li class="site-nav__item" data-submenu="legal">
              <a href="https://beta.fec.gov/legal-resources" class="site-nav__link">
                <span class="site-nav__link__title">Legal resources</span>
              </a>
            </li>
            <li class="site-nav__item utility-nav__item">
              <a href="https://beta.fec.gov/calendar" class="site-nav__link">Calendar</a>
            </li>
          </ul>
        </div>
        <button for="nav-toggle" class="js-nav-toggle site-nav__button" aria-controls="nav-main">Menu</button>
        <a title="Home" href="" class="site-title"><span class="u-visually-hidden">Federal Election Commission | United States of America</span></a>
      </nav>

    </header>
    <main id="main">
      <section class="slab slab--neutral slab--home">
        <a style="margin-left: 3rem;" onclick="goBack()">&laquo; Back to previous page</a>
      </section>

    <nav id="submenu" class="container">
        <ul>
          <li>
            <a href="/info/compliance.shtml">
              <span>Help with reporting and compliance</span>
            </a>
          </li>
          <li>
            <a href="/ans/answers.shtml">
              <span>Quick Answers</span>
            </a>
          </li>
          <li>
            <a href="/rad/index.shtml">
              <span>RAD FAQ</span>
            </a>
          </li>
          <li>
            <a href="/general/library.shtml">
              <span>Library</span>
            </a>
          </li>
        </ul>
    </nav>
    <div class="container">
      <div class="message message--info">
        <p>The FEC is currently redesigning its website. This page hasn't been redesigned yet, but it still contains the most up-to-date information.</p>
      </div>
    </div>
<!--ENDNAV-->